name: ar_captcha
description: "Flutter plugin for integrating ARCaptcha, providing a secure and customizable captcha solution for Android, IOS, Web apps."
version: 1.0.6
homepage: https://github.com/fateme-shm/ar_captcha
repository: https://github.com/fateme-shm/ar_captcha
issue_tracker: https://github.com/fateme-shm/ar_captcha/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  web: ^1.1.1
  webview_flutter: ^4.13.0
  modal_bottom_sheet: ^3.0.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

platforms:
  ios:
  web:
  android: